"""add blocked_until

Revision ID: 770fdf2b976e
Revises: 277097b104f4
Create Date: 2026-01-28 04:31:18.574964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770fdf2b976e'
down_revision: Union[str, Sequence[str], None] = '277097b104f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_state', sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_state', 'blocked_until')
    # ### end Alembic commands ###
